name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build and Push Docker Image
      env:
        USER: ${{ secrets.USER }}
        PASS: ${{ secrets.PASS }}
      run: |
        COMMIT_HASH=$(git rev-parse --short HEAD)
        TIMESTAMP=$(date +%Y%m%d%H%M%S)
        IMAGE_NAME=arunvel1988/devops-ci-demo-2026:${COMMIT_HASH}_${TIMESTAMP}
        
        echo "Building Docker image with tag $IMAGE_NAME"
        docker build . --file Dockerfile --tag $IMAGE_NAME
        
        echo $PASS | docker login -u $USER --password-stdin
        docker push $IMAGE_NAME
        
        echo "Docker image pushed: $IMAGE_NAME"
